// The island's Tailwind config.
//
// Scope is the consuming app's own source and nothing else. frappe-ui is a bare
// import here, never compiled from source, and framework's runtime stylesheet
// already carries preflight, the design tokens and every utility frappe-ui's
// own components use. So an island sheet holds exactly the utilities the app's
// own templates ask for — scanning frappe-ui too would re-ship a megabyte the
// shadow root has already adopted.
//
// Preflight is off for the same reason: it is in the runtime sheet, adopted
// into the same shadow root, and duplicating it costs ~10 kB per island for
// nothing. The token block stays — it is small, it makes the island sheet
// self-sufficient, and `:root` → `:host` (in the PostCSS chain, not here) is
// what lets it apply inside the shadow tree at all.
//
// Handed to Tailwind as a file path rather than an object, the way framework's
// runtime build does, because `frappe-ui/tailwind` is not loadable by plain
// node: it is ESM that imports `tailwindcss/plugin`, and tailwind 3 publishes
// no `exports` map for that subpath. Only Tailwind's own config loader resolves
// it. The file is generated because the globs it carries are the app's.

import fs from "node:fs";
import path from "node:path";

/** Source globs scanned when the app names none. */
export const DEFAULT_CONTENT = ["src/**/*.{vue,js,ts,jsx,tsx,html}"];

/** Generated configs live where every other build artefact does. */
const CONFIG_DIR = "node_modules/.island";

/**
 * Write the island's Tailwind config and return its path.
 *
 * @param {string} root      the app's frontend directory
 * @param {string[]} content globs, relative to `root` or absolute
 */
export function writeIslandTailwindConfig(root, content = DEFAULT_CONTENT) {
	const dir = path.join(root, CONFIG_DIR);
	const configPath = path.join(dir, "tailwind.config.mjs");
	const globs = content.map((glob) => path.resolve(root, glob));

	fs.mkdirSync(dir, { recursive: true });
	fs.writeFileSync(
		configPath,
		[
			"// Generated by @framework/ui/vite/island. Do not edit.",
			'import preset from "frappe-ui/tailwind";',
			"",
			"// The preset safelists `prose` and `prose-v3` — 75 kB of typography",
			"// rules the runtime sheet already carries. Safelists concatenate",
			"// across presets, so the only way to leave them out is to hand",
			"// Tailwind a preset without one.",
			"const { safelist, ...islandPreset } = preset;",
			"",
			"export default {",
			"	presets: [islandPreset],",
			// Matches the runtime sheet's theme container, so an island's `dark:`
			// utilities and the runtime's flip on the same attribute.
			'	darkMode: ["selector", \'[data-theme="dark"]\'],',
			`	content: ${JSON.stringify(globs, null, 1).replace(/\n/g, "\n\t")},`,
			"	corePlugins: { preflight: false },",
			"	theme: { extend: {} },",
			"};",
			"",
		].join("\n")
	);

	return configPath;
}
