// The island's Tailwind config: the app's own source scanned, and nothing else.
// The runtime sheet is adopted into the same shadow root and already carries
// preflight and every utility frappe-ui's components use.

import fs from "node:fs";
import path from "node:path";

/** Source globs scanned when the app names none. */
export const DEFAULT_CONTENT = ["src/**/*.{vue,js,ts,jsx,tsx,html}"];

/** Generated configs live where every other build artefact does. */
const CONFIG_DIR = "node_modules/.island";

/**
 * Write the island's Tailwind config and return its path.
 *
 * A generated file rather than a config object, because `frappe-ui/tailwind` is
 * ESM importing `tailwindcss/plugin`, and tailwind 3 publishes no `exports`
 * entry for that subpath — only Tailwind's own config loader resolves it. Hence
 * plugins by module specifier too: nothing held in memory survives the trip
 * through a file. The file sits in the app's `node_modules`, so a bare specifier
 * resolves against the app's dependencies.
 *
 * @param {string} root the app's frontend directory
 * @param {Object} [options]
 * @param {string[]} [options.content]   globs, relative to `root` or absolute
 * @param {string[]} [options.tailwindPlugins]  Tailwind plugins, by module specifier
 * @param {string[]} [options.blocklist] classes the island sheet must not generate
 */
export function writeIslandTailwindConfig(root, options = {}) {
	const { content = DEFAULT_CONTENT, tailwindPlugins = [], blocklist = [] } = options;
	const dir = path.join(root, CONFIG_DIR);
	const configPath = path.join(dir, "tailwind.config.mjs");
	const globs = content.map((glob) => path.resolve(root, glob));
	const pluginNames = tailwindPlugins.map((_, index) => `plugin${index}`);

	fs.mkdirSync(dir, { recursive: true });
	fs.writeFileSync(
		configPath,
		[
			"// Generated by @framework/ui/vite/island. Do not edit.",
			'import preset from "frappe-ui/tailwind";',
			...tailwindPlugins.map(
				(specifier, index) =>
					`import ${pluginNames[index]} from ${JSON.stringify(specifier)};`
			),
			"",
			"// The preset safelists `prose` and `prose-v3` — 75 kB of typography",
			"// rules the runtime sheet already carries. Safelists concatenate",
			"// across presets, so the only way to leave them out is to hand",
			"// Tailwind a preset without one.",
			"const { safelist, ...islandPreset } = preset;",
			"",
			"export default {",
			"	presets: [islandPreset],",
			// Matches the runtime sheet's theme container, so an island's `dark:`
			// utilities and the runtime's flip on the same attribute.
			'	darkMode: ["selector", \'[data-theme="dark"]\'],',
			`	content: ${JSON.stringify(globs, null, 1).replace(/\n/g, "\n\t")},`,
			// The app's own plugins, without which its `@container` and the like
			// compile to nothing here while working in its SPA build.
			`	plugins: [${pluginNames.join(", ")}],`,
			`	blocklist: ${JSON.stringify(blocklist)},`,
			"	corePlugins: { preflight: false },",
			"	theme: { extend: {} },",
			"};",
			"",
		].join("\n")
	);

	return configPath;
}
